[package]
name = "Oxidation"
version = "0.0.1"
authors = ["Ryan Jones-Ward <sciguyryan@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
